version: "3.8"
services:
  spring_api:
    container_name: spring_api_rest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - type: bind
        source: "./data"
        target: "/usr/app/data"
    restart: "on-failure"